### ISSUE TITLE
Throw an exception when the BatchWriter fails on a write operation

### ISSUE THREAD

**Issue by sastafford** [rjrudin/ml-javaclient-util#51]
As a developer
I want to TITLE
So that I can handle the exception appropriately and continue to write the next batch.

I have ran into a Batch error where I have a conflicting update error (the batch of documents have two docs with the same URI).  Unfortunately it causes the whole program to crash.  I would like to take note and log the error but I would like the program to continue.  

I believe it is just adding a throws statement on the BatchWriter.write() method.

**Comment by sastafford** [comment]
Looking into this a bit more, one option would be to create a try/catch in RestBatchWriter.  I'm approaching this from MarkLogicItemWriter using this service.  Who should handle the exception?

**Comment by rjrudin** [comment]
I think a Listener interface is appropriate here. I thought that ThreadPoolTaskExecutor had such a thing - it does, but it requires attaching a FailureCallback to the ListenableFuture that's returned. Since subclasses of BatchWriterSupport aren't guaranteed to be doing async writes, I think a listener interface is appropriate here.

**Comment by rjrudin** [comment]
@sastafford How does this look?

https://github.com/rjrudin/ml-javaclient-util/commit/b0d59cfb27bad3d9068a5497642e4a529292d73c

I don't think anything is needed when a non-async TaskExecutor is used, as the client can just use a try/catch itself.
